language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: npm
    email: me@piyushmehta.com
    api_key:
      secure: TbQLAlf1zh5NKLym+JxRi1XUnR7LtnISOsOfxxPdJTORaH/DUMywuNl4XHIMvLln0Fk/oRtJCBl2afBuASGbVPTGlDfbj3ytwRHcLmPFRpSJ96gpShBLa3YVhnOre7EUpjoBpCA7iF+jfEEjXI4T/AdbRbmiwHMRcIHQcCSy4OeuL9EfWRM9BtPD2zRku/i2p7zD+N0zOvxYgMJErK3JfdxZQTsGI959irUpy6LeEDNH6Id+oEMriaDhrcryOYBWhpJgvr4jE55UiEcRKECfjrDPDzP7CFI8GgVhB6yBPC9xn1WlqyfCw/GF6IHEdQakLbfCSHl521dSbS/WkBccpK1MYFqaUBPJzF5fspMF3isDs5tSCmSRVVkIWfl5jGnDfWHeNpO0TQfqNzxt+qA5WYXh6eaIfZN7BAPx/aMr6gM837R8GTGE4zBRy4NROUgYp1fLByowZfjw/V198yLIi5cyFfM0FJt+bzwW7aG08WBBiEsa3Dnrn8cG9YcW5zJEAiC0mJ8WJHCrQ+7+Q3meI7Kh3KDXc69tnaWqpqHdSxmRf0XAyAL7QY7O67/MDoZmLDY42+4OVJtoh3CnrhkifmzdudIE3zPqHHUDO2eBRpgvu4xY76j+m6feRe1QzbnTtzRGm6xi6Gd5BoE8Ja0IGjb89a6bL1RjnrDLBfm5oaM=
    on:
      repo: zapify-ui/zapify
      branch: Staging
  - provider: script
    script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
    skip_cleanup: true
    on:
      branch: Staging