language: node_js
node_js:
- stable
install:
  - npm install
cache:
  directories:
  - node_modules
  - storybook-static
script:
- npm run test
- npm run build
- ./node_modules/.bin/codecov --token="fb6b058a-5c4f-40c9-a5ff-d351fda90dd0"    
after_success:
  - npm run build-storybook
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $github_token
  local_dir: storybook-static
  repo: arnabk/zapify
  target_branch: gh-pages
  on:
    branch: master

- provider: npm
  email: me@piyushmehta.com
  on:
    repo: zapify-ui/zapify
    branch: master
